cluster.name: suricata-cluster

node.name: elk-server

path.data: /var/lib/elasticsearch
path.logs: /var/log/elasticsearch

network.host: 0.0.0.0
http.port: 9200

discovery.type: single-node

xpack.security.enabled: false

action.destructive_requires_name: true
