input {
  udp {
    port => 514
    type => "syslog"
  }
}

filter {
  if [type] == "syslog" {

    json {
      source => "message"
      skip_on_invalid_json => true
    }

    mutate {
      add_field => {
        "event_source" => "Suricata"
      }
    }

    date {
      match => ["timestamp","ISO8601"]
      target => "@timestamp"
    }
  }
}

output {

  elasticsearch {
    hosts => ["http://localhost:9200"]
    index => "suricata-%{+YYYY.MM.dd}"
  }

  stdout {
    codec => rubydebug
  }

}
